### ISSUE TITLE
Processing of templates clobbers newlines

### ISSUE THREAD

**Issue by tomwmth** [KyoriPowered/blossom#86]
The resource template:

```yml
main: dev.tomwmth.test.Plugin
name: {{ name }}
version: {{ version }}
author: tomwmth
api-version: 1.13
```

will become the following after being processed by Blossom:

```yml
main: dev.tomwmth.test.Plugin
name: TestPluginversion: 1.0-SNAPSHOTauthor: tomwmth
api-version: 1.13
```

Here is a minimal project that reproduces the issue: [blossom-newline-bug.zip](https://github.com/user-attachments/files/20431667/blossom-newline-bug.zip)

**Comment by zml2008** [comment]
Ah, looks like [this setting](https://javadoc.io/static/io.pebbletemplates/pebble/3.2.4/io/pebbletemplates/pebble/PebbleEngine.Builder.html#newLineTrimming(boolean)) is set incorrectly. I'll push out a new release, in the meantime you can surround the values with quotes to avoid this issue, so you'd have something like:

```yaml
main: dev.tomwmth.test.Plugin
name: "{{ name }}"
version: "{{ version }}"
author: tomwmth
api-version: 1.13
```
